name: Push GitHub, Build e Push Docker Hub

on:
  push:
    branch: main  

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v1
        with:
          repository: luickcarvalho/api-starwars
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Update
        run: sudo apt-get update

      - name: Install Make 
        run: sudo apt-get install make -y

      - name: Install Docker
        run: sudo apt-get install docker.io -y
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Acessar DIR
        run: cd api-starwars/kub-ans-ope-gt-api/ 
    
      - name: Build e push
        run:  make docker-build docker-push