name: Push GitHub, Build e Push Docker Hub
on:
  push:
    branches: main
  paths:
      - kub-ans-ope-gt-api/**
  
  pull_request:
    branches: main
    paths:
      - kub-ans-ope-gt-api/**

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kub-ans-ope-gt-api
        shell: bash
    
    steps:
      #- name: Clonar Repositorio
      #  run: git clone https://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@github.com/luickcarvalho/api-starwars
      
      - name: Update
        run: sudo apt-get update

      - name: Install Make 
        run: sudo apt-get install make -y

      - name: Install Docker
        run: sudo curl https://releases.rancher.com/install-docker/19.03.sh | sh
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build
        run: docker build -t luickcarvalho/api-starwars:latest .
      
      - name: push
        run: docker push luickcarvalho/api-starwars:latest